### ISSUE TITLE
'accounts' application should be first

### ISSUE THREAD

**Issue by mlier** [wsvincent/django-auth-tutorial#7]
"accounts" application should be first in INSTALLED_APPS list.
Otherwise, html template files will not be take into account and admin template are displayed.

```
INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```

**Comment by wsvincent** [comment]
Hi @mlier,

I don't think this is correct. We're overriding templates manually in the example so the order of apps isn't as important. The default templates from Django are used unless we explicitly override them. But... maybe I've missed something. If you have code and screenshots to share, I'm always curious to learn :)
